// This file is AUTO-GENERATED by scripts/sync_tokens.js
// Do not edit directly. Edit tokens/colors.json instead.

module.exports = {
  "gray": {
    "100": "#F3F4F6",
    "400": "#9CA3AF",
    "500": "#6B7280",
    "700": "#374151",
    "800": "#1F2937",
    "900": "#111827",
    "950": "#030712"
  },
  "blue": {
    "400": "#60A5FA",
    "500": "#3B82F6"
  },
  "cyan": {
    "400": "#22D3EE"
  },
  "purple": {
    "400": "#C084FC",
    "500": "#A855F7"
  },
  "pink": {
    "400": "#F472B6",
    "500": "#EC4899"
  },
  "orange": {
    "400": "#FB923C",
    "500": "#F97316"
  },
  "emerald": {
    "500": "#10B981"
  },
  "green": {
    "400": "#4ADE80",
    "500": "#22C55E"
  },
  "yellow": {
    "200": "#FEF08A",
    "400": "#FACC15",
    "500": "#EAB308"
  },
  "red": {
    "400": "#F87171",
    "500": "#EF4444"
  }
};
